apiVersion: batch/v1
kind: CronJob
metadata:
  name: filestore-backup
  namespace: filestore-backup
spec:
  schedule: "0 0 * * *" # Every day once
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600 # 1 hour
      template:
        spec:
          seviceaccountName: filestore-backup
          containers:
          - name: filestore-backup
            image: filestore-backup:v1.0.1
            imagePullPolicy: IfNotPresent
            env:
            - name: GCP_PROJECT_ID
              value: "example-project-1"
            - name: GCP_REGION
              value: "region"
            # if filestore instance in tier REGIONAL then zone will be same as region
            - name: GCP_ZONE
              value: "region-a"
            - name: GCP_FILESTORE_INSTANCE
              value: "filestore-1"
            # Env var to use if using GCP service account JSON key for auth
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/var/secrets/filestore-backup-sa.json"
            - name: GCP_FILESTORE_SHARE_NAME
              value: "example"
            - name: BACKUP_DURATION
              value: "168"
            volumeMounts:
            # Mount the secret to the container
            - name: secret-volume
              mountPath: "/var/secrets"
              readOnly: true
          volumes:
          # Define the secret volume reference created in secret.yaml
          - name: secret-volume
            secret:
              secretName: filestore-backup
          restartPolicy: OnFailure
