# Example secret for when auth with GCP service account JSON key.
apiVersion: v1
kind: Secret
metadata:
  name: filestore-backup
  namespace: filestore-backup
data:
  filestore-backup-sa: "base64 encoded service account JSON key value to do commit to git"
