# Example service account for when using workload identity with GKE for auth.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filestore-backup
  namespace: filestore-backup
  annotations:
    iam.gke.io/gcp-service-account: "filestore-backup@<PROJECT_ID>.iam.gserviceaccount.com"
